name: spacegame
description: Space Game
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ^3.13.0

dependencies:
  flame: ^1.28.0
  flame_lint: ^1.3.0
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/consumables/flight.png
    - assets/images/player/alien_fly.png
    - assets/images/player/alien_idle_flap.png


